name: "Build OpenCV releases"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-opencv:
    defaults:
      run:
        working-directory: ./
  
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-22.04.
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Prepare for llvm
        if: matrix.platform != 'windows-latest'
        run: rm -rf ${{ runner.temp }}/llvm # Make sure directory doesn't exist
      
      - name: Install LLVM and Clang MacOS on arm
        uses: KyleMayes/install-llvm-action@v2
        if: ${{ matrix.platform == 'macos-latest' && matrix.args == '--target aarch64-apple-darwin' }}
        with:
          version: "15.0.7"
          arch: arm64
          directory: ${{ runner.temp }}/llvm

      - name: Install LLVM and Clang MacOS on x64
        uses: KyleMayes/install-llvm-action@v2
        if: ${{ matrix.platform == 'macos-latest' && matrix.args == '--target x86_64-apple-darwin' }}
        with:
          version: "15.0.7"
          arch: x64
          directory: ${{ runner.temp }}/llvm

      - name: Install LLVM and Clang Ubuntu x64 
        uses: KyleMayes/install-llvm-action@v2
        if: matrix.platform == 'ubuntu-22.04'
        with:
          version: "18.1.8"
          arch: x64
          directory: ${{ runner.temp }}/llvm

      - name: Install LLVM and Clang Windows x64 
        uses: KyleMayes/install-llvm-action@v2
        if: matrix.platform == 'windows-latest'
        with:
          version: "18.1.8"
          arch: x64
          directory: ${{ runner.temp }}/llvm
      
      - name: Get cmake
        uses: lukka/get-cmake@latest

      - name: Clone OpenCV
        run: git clone https://github.com/opencv/opencv.git
      
      - name: Configure OpenCV
        if: matrix.platform != 'windows-latest'
        working-directory: ./opencv
        run: |
          mkdir build
          cd build/
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }} ..
     
      - name: Configure and Build OpenCV Windows
        working-directory: ./opencv/
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir build
          cd build/
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }} ..
          make -j2
          make install

      - name: Build OpenCV Other OS
        working-directory: ./opencv/build
        if: matrix.platform != 'windows-latest'
        run: |
          make -j$(nproc)
          sudo make install

      # Export the desired folder (opencv2) as an artifact
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: "OpenCV Release v${{ github.run_number }}"
          body: "Automatically generated release"
          files: |
            ./export/opencv2