name: "build-opencv"

on:
  push:
    branches: [opencv]

jobs:
  build-opencv:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-22.04.
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        if: matrix.platform == 'macos-latest' && 'aarch64-apple-darwin'
        with:
          version: "18.1.8"
          arch: arm64
        if: matrix.platform == 'macos-latest' && 'x86_64-apple-darwin'
        with:
          version: "15.0.7"
          arch: x64
        if: matrix.platform == 'ubuntu-22.04'
        with:
          version: "18.1.8"
          arch: x64
        if: matrix.platform == 'windows-latest'
        with:
          version: "19.1.7"
          arch: x64
      
      - name: Get cmake
        uses: lukka/get-cmake@latest

      - name: Clone OpenCV
        run: git clone https://github.com/opencv/opencv.git
      
      - name: Configure OpenCV
        run: |
          mkdir opencv/build
          cd opencv/build
          cmake ..
     
      - name: Build OpenCV
        if: matrix.platform == 'windows-latest'
        run: | 
          make -j%NUMBER_OF_PROCESSORS%
          make install
        if: matrix.platform != 'windows-latest'
        run: |
          make -j$(nproc)

      - name: make install OpenCV
        run: make install
        
        