name: C++ Server CI

on:
  push:
    branches: [main, testing, dev]
    paths:
      - "server/**"
      - ".github/workflows/format_check_server.yml"
  pull_request:
    branches: [main, testing, dev]
    paths:
      - "server/**"
      - ".github/workflows/format_check_server.yml"

jobs:
  lint-and-format-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy clang-format cmake libgtest-dev

          git submodule init
          git submodule update --remote

      - name: Run clang-format (will probably change this script)
        run: |
          #!/bin/bash

          FORMATTING_ISSUES=0
          FILES_WITH_ISSUES=""

          FOUND_FILES=$(find . -not -path "./build/*" -regex ".*\.\(cpp\|hpp\|cc\|cxx\|h\)")

          for file in $FOUND_FILES; do
            if ! clang-format -style=file "$file" --dry-run --Werror 2>&1; then
              FORMATTING_ISSUES=1
              FILES_WITH_ISSUES="$FILES_WITH_ISSUES\n  - $file"
            fi
          done

          if [ $FORMATTING_ISSUES -ne 0 ]; then
            echo "=========================="
            echo "❌ FORMATTING CHECK FAILED"
            echo "Formatting issues found in the following files:"
            echo -e "$FILES_WITH_ISSUES"
            echo ""
            echo "Run this command from the server dir to fix these issues:"
            echo "find . -not -path \"./build/*\" -regex \".*\.\(cpp\|hpp\|cc\|cxx\|h\)\" -exec clang-format -style=file -i {} \;"
            exit 1
          else
            echo "=========================="
            echo "✅ FORMATTING CHECK PASSED"
            echo "All files are properly formatted."
            exit 0
          fi

      - name: Configure cmaake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

      - name: Run clang-tidy
        run: |
          clang-tidy -p build --warnings-as-errors='*' $(find . -not -path "./build/*" -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)')

  build-and-test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev

          git submodule init
          git submodule update --remote

      - name: Configure cmake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Test
        run: |
          cd build
          ctest --verbose
